apiVersion: v1
kind: Service
metadata:
  name: udm-argocd-clusterip
  namespace: udm-cnf1
  labels:
    app: udm
    type: internal-lb
    managed-by: argocd
spec:
  selector:
    app: udm
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: udm-argocd-nodeport
  namespace: udm-cnf1
  labels:
    app: udm
    type: external-access
    managed-by: argocd
spec:
  selector:
    app: udm
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort
