apiVersion: v1
kind: Service
metadata:
  name: hss-argocd-clusterip
  namespace: hss-cnf1
  labels:
    app: hss
    type: internal-lb
    managed-by: argocd
spec:
  selector:
    app: hss
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hss-argocd-nodeport
  namespace: hss-cnf1
  labels:
    app: hss
    type: external-access
    managed-by: argocd
spec:
  selector:
    app: hss
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
