apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drf-site2
  namespace: argocd
  labels:
    product: drf
    site: site2
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaniaYousfi11/pfe-gitops.git
    targetRevision: main
    path: apps/drf/site2
  destination:
    name: site2
    namespace: drf-cnf1
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
