apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hss-site1
  namespace: argocd
  labels:
    product: hss
    site: site1
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RaniaYousfi11/pfe-gitops.git
    targetRevision: main
    path: apps/hss/site1
  destination:
    server: https://kubernetes.default.svc
    namespace: hss-cnf1
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
