apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udm-site1
  namespace: argocd
  labels:
    product: udm
    site: site1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RaniaYousfi11/pfe-gitops.git
    targetRevision: main
    path: apps/udm/site1
  destination:
    server: https://kubernetes.default.svc
    namespace: udm-cnf1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
