apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: raniayousfi11/pfe-cnf-app
    newName: raniayousfi11/pfe-cnf-app
    newTag: 07870df
